version: '3'

services:
  go-app:
    image: golang:1.19
    ports:
      - "8085:8080"
    # environment:
    #   GIN_MODE: release
    volumes:
      - "./:/usr/src/app"
    working_dir: /usr/src/app
    tty: true
    networks:
      - backend
  mysql:
    image: mysql:5.7
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    restart: always
    ports:
      - "33063:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - "./data/mysql:/var/lib/mysql"
    networks:
      - backend
  redis:
    image: redis:latest
    volumes:
      - "./data/redis:/data"
    ports:
      - "63793:6379"
    networks:
      - backend

networks:
  backend: